Build training pipeline using configuration files

diff --git a/mlops-pipelines/2-training-code-build/training-code-build-pipeline.yml b/mlops-pipelines/2-training-code-build/training-code-build-pipeline.yml
--- a/mlops-pipelines/2-training-code-build/training-code-build-pipeline.yml
+++ b/mlops-pipelines/2-training-code-build/training-code-build-pipeline.yml
@@ -9,13 +9,15 @@
 #     - v2-preview
 #   paths:
 #     include:
-#     - Custom_Script/mlops-pipelines/2-training-code-build/*
-#     - Custom_Script/mlops-pipelines/scripts/create_training_pipeline.py
-#     - Custom_Script/scripts/train.py
-#     - Custom_Script/scripts/train.conda.yml
+#     - mlops-pipelines/2-training-code-build/*
+#     - mlops-pipelines/scripts/create_training_pipeline.py
+#     - mlops-pipelines/configuration/*/script-settings.yml
+#     - mlops-pipelines/configuration/*/train-parallelrunstep-config.yml
+#     - scripts/*/train.py
+#     - scripts/*/train.conda.yml
 
 variables:
-- template: ../many-models-variables.yml
+- template: ../configuration/many-models-variables.yml
 - group: manymodels-vg
 
 pool:
@@ -25,8 +27,20 @@ stages:
 - stage: build_training
   displayName: 'Publish Training AML Pipeline'
   jobs:
+  
+    - job: check_training_method
+      displayName: 'Check Training Method'
+      steps:
+        - bash: |
+            if [ "$TRAINING_METHOD" != "automl" ] && [ "$TRAINING_METHOD" != "customscript" ]; then
+              >&2 echo "Error: variable TRAINING_METHOD must be set to 'automl' or 'customscript'"
+            fi
+          displayName: 'Check Training Method'
+          failOnStderr: true
+
     - job: build_training
       displayName: 'Publish Training AML Pipeline'
+      dependsOn: check_training_method
       steps:
 
         - task: UsePythonVersion@0
@@ -41,14 +55,16 @@ stages:
             scriptLocation: inlineScript
             inlineScript: |
               # Install dependencies
-              python -m pip install --upgrade pip && python -m pip install azureml-sdk[contrib]==$SDK_VERSION
+              python -m pip install --upgrade pip && python -m pip install pyyaml azureml-sdk==$SDK_VERSION
               # Create/update training pipeline
-              trainingbuild_script=Custom_Script/mlops-pipelines/scripts/create_training_pipeline.py
+              trainingbuild_script=mlops-pipelines/scripts/create_training_pipeline.py
               python $trainingbuild_script --name $(AML_TRAINING_PIPELINE_NAME) \
                                            --version $(Build.BuildId) \
+                                           --scripts-dir 'scripts/$(TRAINING_METHOD)/' \
+                                           --scripts-settings 'mlops-pipelines/configuration/$(TRAINING_METHOD)/script-settings.yml' \
+                                           --prs-config 'mlops-pipelines/configuration/$(TRAINING_METHOD)/train-parallelrunstep-config.yml' \
                                            --dataset $(AML_DATASET_NAME)_train \
                                            --compute $(AML_COMPUTE_NAME) \
                                            --subscription-id $(az account show --query id -o tsv) \
                                            --resource-group $(RESOURCE_GROUP) \
                                            --workspace-name $(AMLWORKSPACE_NAME)
-
